### ISSUE TITLE
Issue when running this script in other OS than Windows

### ISSUE THREAD

**Issue by Chiheb-Nexus** [gurukiran07/snake-game#1]
Also, if we install this script under other directory than desktop and within another user, wich will be the case, this script won't find the right path.

https://github.com/gurukiran07/snake-game/blob/9eeec950d1e92b6ae1cd653071e5ceb333661944/SnakeGameOOP.py#L20

Same for other pathes for PNG files.

Hint: why not using `os.path` ? and get the absolute path for the running file and then you can build the correct script for whatever the OS the user is running ?

**Comment by gurukiran07** [comment]
Thanks for the comment. Yes, `os.getcwd`+`'image_name'` solves the issue. Actually I built this game for making a Snake game bot and this a very earlier stage of the game. I improved the game and the newer version is maintainable than this. You can find the full repository here [https://github.com/khalil192/snake-game-bot](snake-game-bot). Have look at it and any suggested/tips are much appreciated. I'll make sure to update this repository with the current version we are the using. Thanks.
